# Generated by Django 5.1.1 on 2024-10-01 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_finder", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=255)),
                ("rating", models.FloatField()),
                ("text", models.TextField()),
                ("relative_time_description", models.CharField(max_length=255)),
                (
                    "favorite_restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="food_finder.favoriterestaurant",
                    ),
                ),
            ],
        ),
    ]
