# Generated by Django 4.2.16 on 2024-09-15 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_finder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='Restaurant_geolocation',
        ),
    ]
