# Generated by Django 4.2.16 on 2024-09-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_finder', '0002_rename_restaurant_restaurant_geolocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cuisine_type', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('details', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant_geolocation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='restaurant_geolocation',
            name='details',
        ),
        migrations.RemoveField(
            model_name='restaurant_geolocation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='restaurant_geolocation',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='restaurant_geolocation',
            name='name',
        ),
    ]
