# Generated by Django 5.1.1 on 2024-10-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_finder", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="favoriterestaurant",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
