# Generated by Django 5.1.1 on 2024-10-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_finder", "0003_favoriterestaurant_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="favoriterestaurant",
            name="cuisine_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
