# Generated by Django 5.1.1 on 2024-10-01 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food_finder", "0004_favoriterestaurant_cuisine_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favoriterestaurant",
            name="cuisine_type",
        ),
    ]
