# Generated by Django 4.2.16 on 2024-09-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_finder', '0004_like_restaurantgeolocation_delete_restaurant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cuisine_type', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('distance', models.FloatField()),
            ],
        ),
    ]
