# Generated by Django 5.1.1 on 2024-10-01 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_finder", "0005_restaurant_restaurant_geolocation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteRestaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_id", models.CharField(max_length=255, unique=True)),
                ("restaurant_name", models.CharField(max_length=255)),
                ("restaurant_address", models.CharField(max_length=255)),
                ("restaurant_rating", models.FloatField()),
                (
                    "restaurant_photo_reference",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
