# Generated by Django 4.2.16 on 2024-10-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_finder', '0005_restaurant'),
        ('food_finder', '0006_favoriterestaurant'),
    ]

    operations = [
    ]
