# Generated by Django 4.2.16 on 2024-10-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_finder', '0007_merge_0005_restaurant_0006_favoriterestaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriterestaurant',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favoriterestaurant',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
