# Generated by Django 4.2.16 on 2024-10-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_finder', '0009_alter_favoriterestaurant_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterestaurant',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='favoriterestaurant',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
