# Generated by Django 4.2.15 on 2024-10-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_finder", "0009_remove_favoriterestaurant_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="favoriterestaurant",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="favoriterestaurant",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
